#!/bin/sh
# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

set -e

case "$1" in
  (configure)
    # create group
    id -g bitmark-data-donation > /dev/null 2>&1 || addgroup --system bitmark-data-donation
    # create user
    id bitmark-data-donation > /dev/null 2>&1 || \
      adduser --system --home /var/run/bitmark-data-donation \
              --disabled-password \
              --gecos "Bitmark user for bitmark-data-donation" \
              --ingroup bitmark-data-donation bitmark-data-donation

    log_dir=/var/lib/bitmark-data-donation/logs
    [ -d "${log_dir}" ] || mkdir "${log_dir}"
    chown bitmark-data-donation:bitmark-data-donation "${log_dir}"
    # enable the unit, but don't start it
    [ -x /bin/systemctl ] && systemctl enable bitmark-data-donation.service >/dev/null 2>&1 || true
    ;;

  (abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  (*)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
