language: swift
osx_image: xcode10
xcode_sdk: iphonesimulator12.0
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_1721088a34b3_key -iv $encrypted_1721088a34b3_iv -in .travis/ssh-deploy.sh.enc -out ssh-deploy.sh -d
- chmod +x ssh-deploy.sh
- ./ssh-deploy.sh
- gem install fastlane
install:
- fastlane add_plugin latest_hockey_build_number
script:
- fastlane ios developtravis
after_success: 
