language: swift
osx_image: xcode10.1
xcode_sdk: iphoneos12.1
node_js:
- '8'
branches:
  only:
  - devel
  - ux-loop
  - master
    
before_install:
- openssl aes-256-cbc -K $encrypted_1721088a34b3_key -iv $encrypted_1721088a34b3_iv -in .travis/secret.tar.enc -out secret.tar -d
- tar xvf secret.tar
- chmod +x ssh-deploy.sh
- ./ssh-deploy.sh
- gem install fastlane
install:
- fastlane add_plugin latest_hockey_build_number
- fastlane add_plugin sentry
script:
- |
    if [ $TRAVIS_BRANCH == "master" ]; then
      fastlane ios betatravis
    else
      fastlane ios developtravis
    fi
after_success: 
