language: swift
osx_image: xcode10
xcode_sdk: iphonesimulator12.0
node_js: 
  - "8"
branches:
  only:
    - master

before_install:
  - openssl aes-256-cbc -K $encrypted_5c13274db47d_key -iv $encrypted_5c13274db47d_iv -in github_deploy_key.enc -out github_deploy_key -d
  - gem install fastlane

install:
  - fastlane add_plugin latest_hockey_build_number

script:
  - fastlane ios betatravis
after_success: