language: swift
osx_image: xcode10
xcode_sdk: iphonesimulator12.0
node_js: 
  - "8"
branches:
  only:
    - master

before_install:
  - gem install fastlane

install:
  - fastlane add_plugin latest_hockey_build_number

script:
  - fastlane ios betatravis
after_success: