apiVersion: v1
kind: Namespace
metadata:
  name: mobile
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: push-notification-config
  namespace: mobile
data:
  config-primary.yaml: "{{ lookup('template', 'gorush-config-primary.yaml') | b64encode }}"
  config-beta.yaml: "{{ lookup('template', 'gorush-config-beta.yaml') | b64encode }}"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: push-notification-primary
  namespace: mobile
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: push-notification
        tier: frontend
    spec:
      containers:
        - image: appleboy/gorush
          name: push-notification
          imagePullPolicy: Always
          ports:
          - containerPort: 8088
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
            - name: config
              mountPath: /config
          command:
              - /bin/gorush
              - -c
              - /config/config.yaml
          resources:
            requests:
              cpu: 0.125
              memory: 256Mi
      volumes:
      - name: config
        secret:
          secretName: push-notification-config
          items:
            - key: config-primary.yaml
              path: config.yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: push-notification-beta
  namespace: mobile
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: push-notification
        tier: frontend
    spec:
      containers:
        - image: appleboy/gorush
          name: push-notification
          imagePullPolicy: Always
          ports:
          - containerPort: 8088
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
            - name: config
              mountPath: /config
          command:
              - /bin/gorush
              - -c
              - /config/config.yaml
          resources:
            requests:
              cpu: 0.125
              memory: 256Mi
      volumes:
      - name: config
        secret:
          secretName: push-notification-config
          items:
            - key: config-primary.yaml
              path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: push-notification-primary
  namespace: mobile
  labels:
    app: push-notification-primary
    tier: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: push-notification-primary
---
apiVersion: v1
kind: Service
metadata:
  name: push-notification-beta
  namespace: mobile
  labels:
    app: push-notification-beta
    tier: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: push-notification-beta