platform :ios, '11.0'

def pods
    # Pods for BitmarkHealthPlus
    
    pod 'BitmarkSDK', :git => 'https://github.com/bitmark-inc/bitmark-sdk-swift.git', :branch => 'v1'
    pod 'KeychainAccess'
    pod 'Intercom'
    pod 'TesseractOCRiOS', :git => 'https://github.com/gali8/Tesseract-OCR-iOS.git'
    pod 'iCloudDocumentSync'
    
end

target 'BitmarkHealthPlus' do
  use_frameworks!

  pods

  target 'BitmarkHealthPlusTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BitmarkHealthPlus dev' do
    use_frameworks!
    
    pods
    
end

target 'BitmarkHealthPlus beta' do
    use_frameworks!
    
    pods
    
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.2'      end
  end
end
