# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

reset_git_repo(
  force: true,
  skip_clean: true
)
git_pull
sh "npm install"

platform :ios do
  desc "Push a new beta build to Hockeyapp"
  lane :appstore do
    version_number = latest_hockey_build_number(
      api_token: ENV['HOCKEYAPP_KEY']
    ).to_i
    increment_build_number(
      xcodeproj: "ios/BitmarkHealthPlus.xcodeproj",
      build_number: (version_number + 1).to_i
    )
    cert
    sigh(
      force: false,
      adhoc: true
    )
    build_app(
      export_options: {iCloudContainerEnvironment: 'Production'},
      workspace: "ios/BitmarkHealthPlus.xcworkspace", 
      scheme: "BitmarkHealthPlus",
      include_bitcode: false
    )
    hockey(
      api_token: ENV['HOCKEYAPP_KEY']
    )
  end
  lane :beta do
    version_number = latest_hockey_build_number(
      api_token: ENV['HOCKEYAPP_KEY']
    ).to_i
    increment_build_number(
      xcodeproj: "ios/BitmarkHealthPlus.xcodeproj",
      build_number: (version_number + 1).to_i
    )
    cert
    sigh(
      force: false
    )
    build_app(
      export_options: {iCloudContainerEnvironment: 'Production'},
      workspace: "ios/BitmarkHealthPlus.xcworkspace", 
      scheme: "BitmarkHealthPlus beta",
      include_bitcode: false
    )
    hockey(
      api_token: ENV['HOCKEYAPP_KEY']
      )
  end
  lane :alpha do
    version_number = latest_hockey_build_number(
      api_token: ENV['HOCKEYAPP_KEY']
    ).to_i
    increment_build_number(
      xcodeproj: "ios/BitmarkHealthPlus.xcodeproj",
      build_number: (version_number + 1).to_i
    )
    cert
    sigh(
      force: false
    )
    build_app(
      export_options: {iCloudContainerEnvironment: 'Production'},
      workspace: "ios/BitmarkHealthPlus.xcworkspace", 
      scheme: "BitmarkHealthPlus dev",
      include_bitcode: false
    )
    hockey(
      api_token: ENV['HOCKEYAPP_KEY']
      )
  end
  lane :beta-travis do
    keychain_name = "ios-build.keychain"
    keychain_password = SecureRandom.base64

    version_number = latest_hockey_build_number(
      api_token: ENV['HOCKEYAPP_KEY']
    ).to_i
    increment_build_number(
      xcodeproj: "ios/BitmarkHealthPlus.xcodeproj",
      build_number: (version_number + 1).to_i
    )
    create_keychain(
      name: keychain_name,
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    import_certificate(
      certificate_path: "fastlane/cer/enterprise.p12",
      certificate_password: ENV["KEY_PASSWORD"],
      keychain_name: keychain_name
      keychain_password: keychain_password
    )
    sigh(
      force: false
    )
    build_app(
      export_options: {iCloudContainerEnvironment: 'Production'},
      workspace: "ios/BitmarkHealthPlus.xcworkspace", 
      scheme: "BitmarkHealthPlus dev",
      include_bitcode: true
    )
    hockey(
      api_token: ENV['HOCKEYAPP_KEY']
      )
  end
end