# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to Hockeyapp"

  lane :buildappstore do
    reset_git_repo(
      force: true,
      skip_clean: true
    )
    git_pull
    sh "npm install"
    version_number = latest_hockey_build_number(
      api_token: ENV['HOCKEYAPP_KEY']
    )
    increment_build_number(
      xcodeproj: "ios/BitmarkHealthPlus.xcodeproj",
      build_number: (version_number.to_i + 1)
    )
    cert
    sigh(
      force: false,
      adhoc: true
    )
    build_app(
      export_options: {iCloudContainerEnvironment: 'Production'},
      workspace: "ios/BitmarkHealthPlus.xcworkspace", 
      scheme: "BitmarkHealthPlus",
      include_bitcode: false
    )
    sentry_upload_dsym(
      auth_token: ENV['SENTRY_AUTH_TOKEN'],
      org_slug: 'bitmark-inc',
      project_slug: 'bitmark-health',
      dsym_path: './BitmarkHealthPlus beta.app.dSYM.zip'
    )
    hockey(
      api_token: ENV['HOCKEYAPP_KEY']
    )
  end
  lane :beta do
    reset_git_repo(
      force: true,
      skip_clean: true
    )
    git_pull
    sh "npm install"
    version_number = latest_hockey_build_number(
      api_token: ENV['HOCKEYAPP_KEY']
    )
    increment_build_number(
      xcodeproj: "ios/BitmarkHealthPlus.xcodeproj",
      build_number: (version_number.to_i + 1)
    )
    cert
    sigh(
      force: false
    )
    build_app(
      export_options: {iCloudContainerEnvironment: 'Production'},
      workspace: "ios/BitmarkHealthPlus.xcworkspace", 
      scheme: "BitmarkHealthPlus beta",
      clean: true,
      include_bitcode: false
    )
    sentry_upload_dsym(
      auth_token: '9c23002afc0a42a8b5a674b474b7e1d1b03e67b6ee474d58afd0a7610da34109',
      org_slug: 'bitmark-inc',
      project_slug: 'bitmark-health',
      dsym_path: './BitmarkHealthPlus beta.app.dSYM.zip'
    )
    hockey(
      api_token: ENV['HOCKEYAPP_KEY'],
      release_type: "2",
      tags: "internal_testers"
    )
  end
  lane :alpha do
    reset_git_repo(
      force: true,
      skip_clean: true
    )
    git_pull
    sh "npm install"
    version_number = latest_hockey_build_number(
      api_token: ENV['HOCKEYAPP_KEY']
    )
    increment_build_number(
      xcodeproj: "ios/BitmarkHealthPlus.xcodeproj",
      build_number: (version_number.to_i + 1)
    )
    cert
    sigh(
      force: false
    )
    build_app(
      export_options: {iCloudContainerEnvironment: 'Production'},
      workspace: "ios/BitmarkHealthPlus.xcworkspace", 
      scheme: "BitmarkHealthPlus dev",
      include_bitcode: false
    )
    sentry_upload_dsym(
      auth_token: ENV['SENTRY_AUTH_TOKEN'],
      org_slug: 'bitmark-inc',
      project_slug: 'bitmark-health',
      dsym_path: './BitmarkHealthPlus beta.app.dSYM.zip'
    )
    hockey(
      api_token: ENV['HOCKEYAPP_KEY'],
      notes_type: "1",
      build_server_url: ENV['TRAVIS_JOB_WEB_URL'],
      repository_url: "https://github.com/bitmark-inc/bitmark-mobile-health-plus"
    )
  end
  lane :betatravis do
    sh "npm install"
    keychain_name = "ios-build.keychain"
    keychain_password = SecureRandom.base64

    version_number = latest_hockey_build_number(
      api_token: ENV['HOCKEYAPP_KEY']
    )
    increment_build_number(
      xcodeproj: "ios/BitmarkHealthPlus.xcodeproj",
      build_number: (version_number.to_i + 1)
    )
    create_keychain(
      name: keychain_name,
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    unlock_keychain(
      path: keychain_name,
      password: keychain_password
    )

    match(
      app_identifier: 'com.bitmark.healthplus.beta',
      git_url: 'git@github.com:bitmark-inc/mobile-shared-certificate.git',
      type: 'enterprise',
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      readonly: true
    )

    build_app(
      export_options: {iCloudContainerEnvironment: 'Production'},
      workspace: "ios/BitmarkHealthPlus.xcworkspace", 
      scheme: "BitmarkHealthPlus beta",
      include_bitcode: true
    )
    sentry_upload_dsym(
      auth_token: ENV['SENTRY_AUTH_TOKEN'],
      org_slug: 'bitmark-inc',
      project_slug: 'bitmark-health',
      dsym_path: './BitmarkHealthPlus beta.app.dSYM.zip'
    )
    hockey(
      api_token: ENV['HOCKEYAPP_KEY'],
      release_type: "2",
      tags: "internal_testers",
      )
  end
  lane :developtravis do
    sh "npm install"
    keychain_name = "ios-build.keychain"
    keychain_password = SecureRandom.base64

    version_number = latest_hockey_build_number(
      api_token: ENV['HOCKEYAPP_KEY']
    )
    increment_build_number(
      xcodeproj: "ios/BitmarkHealthPlus.xcodeproj",
      build_number: (version_number.to_i + 1)
    )
    create_keychain(
      name: keychain_name,
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    unlock_keychain(
      path: keychain_name,
      password: keychain_password
    )

    match(
      app_identifier: 'com.bitmark.healthplus.inhouse',
      git_url: 'git@github.com:bitmark-inc/mobile-shared-certificate.git',
      type: 'enterprise',
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      readonly: true
    )

    build_app(
      export_options: {iCloudContainerEnvironment: 'Production'},
      workspace: "ios/BitmarkHealthPlus.xcworkspace", 
      scheme: "BitmarkHealthPlus dev",
      include_bitcode: true
    )

    sentry_upload_dsym(
      auth_token: ENV['SENTRY_AUTH_TOKEN'],
      org_slug: 'bitmark-inc',
      project_slug: 'bitmark-health',
      dsym_path: './BitmarkHealthPlus beta.app.dSYM.zip'
    )

    hockey(
      api_token: ENV['HOCKEYAPP_KEY'],
      notes: "**Branch**: ```" + ENV['TRAVIS_BRANCH'] + "``` --- **CI build**: ```" + ENV['TRAVIS_JOB_WEB_URL'] + "``` --- **Commit message**: ```" + ENV['TRAVIS_COMMIT_MESSAGE'] + "```",
      notes_type: "1",
      build_server_url: ENV['TRAVIS_JOB_WEB_URL'],
      repository_url: "https://github.com/bitmark-inc/bitmark-mobile-health-plus",
      )
  end
end
