apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gorush
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gorush
        tier: frontend
    spec:
      containers:
      - image: appleboy/gorush
        name: gorush
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8088
          initialDelaySeconds: 3
          periodSeconds: 3
        volumeMounts:
            - name: config
              mountPath: /config
        command:
            - /bin/gorush
            - -c 
            - config/config.yaml
        resources:
          requests:
            cpu: 0.125
            memory: 256Mi
      volumes:
      - name: config
        secret:
          secretName: gorush-config
          items:
            - key: config.yaml
              path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: gorush
  labels:
    app: gorush
    tier: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8088
    name: restful
  - port: 9000
    protocol: TCP
    targetPort: 9000
    name: gprc
  selector:
    app: gorush